In [1]:
import numpy  as np

### numpy cookbook

All you quickly need to know about numpy

Dr *Gonzalo Martínez Lema*

January 2020

In [2]:
np.random.seed(2**31)

# Building arrays

https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.array-creation.html

### Constant values

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10, dtype=int) # Force the array to be integers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
a_value = 1.2
np.full(10, a_value)

array([1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2])

### From other sequences

In [6]:
c = [3, 4, 5, 6.333, np.pi]
np.array(c)

array([3.        , 4.        , 5.        , 6.333     , 3.14159265])

In [7]:
np.zeros_like(c)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones_like(c)

array([1., 1., 1., 1., 1.])

In [9]:
np.full_like(c, 4.5)

array([4.5, 4.5, 4.5, 4.5, 4.5])

### Converting to and copying arrays

In [10]:
d = np.asarray(c)
d

array([3.        , 4.        , 5.        , 6.333     , 3.14159265])

In [11]:
d is c

False

In [12]:
np.asarray(d) is d

True

In [13]:
gen = (i**2 for i in range(4))
print(gen)
np.fromiter(gen, dtype=float)

<generator object <genexpr> at 0x7f77f0b9add0>


array([0., 1., 4., 9.])

### Sequences of numbers

In [14]:
start, stop, step = 4, 19, 3
np.arange(start, stop, step) # same as python's range, but returns a np.array

array([ 4,  7, 10, 13, 16])

In [15]:
start, stop, ndiv = 4, 19, 5
np.linspace(start, stop, ndiv) # by default endpoint is included, use endpoint=False for a np.arange-like behaviour

array([ 4.  ,  7.75, 11.5 , 15.25, 19.  ])

In [16]:
np.logspace(-7, 0, 8)

array([1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00])

In [17]:
x = np.arange(5, 10)
y = np.arange(2,  5)
print(x)
print(y)
xx, yy = np.meshgrid(x, y) # x is the inner loop
print(xx)
print(yy)

[5 6 7 8 9]
[2 3 4]
[[5 6 7 8 9]
 [5 6 7 8 9]
 [5 6 7 8 9]]
[[2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [18]:
x = np.arange(5, 10)
y = np.arange(2,  5)
print(x)
print(y)
xx, yy = np.meshgrid(x, y, indexing="ij") # x is the outer loop
print(xx)
print(yy)

[5 6 7 8 9]
[2 3 4]
[[5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]
[[2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]]


### Empty arrays

May be useful for assigning values within a loop

In [19]:
e = np.empty(10)
print(e) # takes whatever is on memory or something like that
for i in range(10):
    e[i] = i**2
print(e)

[1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [20]:
f = np.empty_like(c)
print(f)
for i in range(len(c)):
    f[i] = 4**i
print(f)

[ 4.    7.75 11.5  15.25 19.  ]
[  1.   4.  16.  64. 256.]


### Matrices

In [21]:
np.array([[0, 2],
          [6, 5]])

array([[0, 2],
       [6, 5]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(2, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [25]:
np.eye(4, 4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Manipulating arrays

https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.array-manipulation.html

### Shaping

In [27]:
g = np.arange(9)
print(g)
h = g.reshape(3, 3)
print(h)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
h.flatten() # copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np.ravel(h) # not copied!

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Transposing

In [30]:
h.T # it's a view of the same oject, not a copy

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [31]:
h.transpose() # same as h.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [32]:
i = np.ones((3, 5, 6, 2))
print(i.shape)
j = np.swapaxes(i, 3, 1)
print(j.shape)

(3, 5, 6, 2)
(3, 2, 6, 5)


In [33]:
k = np.rollaxis(i, 2, 0)
print(i.shape)
print(k.shape)

(3, 5, 6, 2)
(6, 3, 5, 2)


### Combining arrays

In [34]:
print(f)
print(g)
np.concatenate([f, g])

[  1.   4.  16.  64. 256.]
[0 1 2 3 4 5 6 7 8]


array([  1.,   4.,  16.,  64., 256.,   0.,   1.,   2.,   3.,   4.,   5.,
         6.,   7.,   8.])

In [35]:
l = np.eye(4, 3)
print(l)
print(h)
print(np.concatenate([l, h]))
print(np.concatenate([l.T, h], axis=1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[1. 0. 0. 0. 0. 1. 2.]
 [0. 1. 0. 0. 3. 4. 5.]
 [0. 0. 1. 0. 6. 7. 8.]]


In [36]:
print(d)
print(f)
print(np.stack([d, f], axis=0)) # axis=0 is the default. concatenate along axis 0

[3.         4.         5.         6.333      3.14159265]
[  1.   4.  16.  64. 256.]
[[  3.           4.           5.           6.333        3.14159265]
 [  1.           4.          16.          64.         256.        ]]


In [37]:
print(d)
print(f)
print(np.stack([d, f], axis=1)) # makes them column vectors and concatenate along axis 1
# check out np.column_stack which does the same and it's more readable for 1-d arrays

[3.         4.         5.         6.333      3.14159265]
[  1.   4.  16.  64. 256.]
[[  3.           1.        ]
 [  4.           4.        ]
 [  5.          16.        ]
 [  6.333       64.        ]
 [  3.14159265 256.        ]]


In [38]:
print(d)
print(f)
print(np.hstack([d, f])) # column-wise stacking

[3.         4.         5.         6.333      3.14159265]
[  1.   4.  16.  64. 256.]
[  3.           4.           5.           6.333        3.14159265
   1.           4.          16.          64.         256.        ]


In [39]:
print(d)
print(f)
print(np.vstack([d, f])) # row-wise stacking

[3.         4.         5.         6.333      3.14159265]
[  1.   4.  16.  64. 256.]
[[  3.           4.           5.           6.333        3.14159265]
 [  1.           4.          16.          64.         256.        ]]


### Exercise: create two 1-D arrays of length 10 and:
- concatenate them
- make them column vectors
- concatenate the column vectors row-wise
- concatenate the column vectors column-wise

### Splitting arrays

In [40]:
print(g)

[0 1 2 3 4 5 6 7 8]


In [41]:
np.split(g, 3) # split in 3, length % n must be 0

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [42]:
np.split(g, (3,)) # split at position 3

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8])]

In [43]:
np.split(g, (3, 8)) # split at positions 3 and 8

[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([8])]

In [44]:
print(h)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
np.split(h, (1,)) # split row-wise. Check np.hsplit

[array([[0, 1, 2]]), array([[3, 4, 5],
        [6, 7, 8]])]

In [46]:
np.split(h, (1,), axis=1) # split column-wise. Check np.vsplit

[array([[0],
        [3],
        [6]]), array([[1, 2],
        [4, 5],
        [7, 8]])]

In [47]:
np.array_split(g, 4) # same as split, but allows length % 0 != 0

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### Exercise: create a 2-D array of shape (5, 3) by splitting a 1-D array and joining the results

### Tiles and repeats

In [48]:
np.tile(4, 5)

array([4, 4, 4, 4, 4])

In [49]:
np.repeat(4, 5)

array([4, 4, 4, 4, 4])

In [50]:
np.tile(np.arange(4), 5)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [51]:
np.repeat(np.arange(4), 5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

### Adding and removing elements

In [52]:
print(f)

[  1.   4.  16.  64. 256.]


In [53]:
np.append(f, 513) # f is not modified. This is a new object

array([  1.,   4.,  16.,  64., 256., 513.])

In [54]:
np.insert(f, 3, -123) # f is not modified. This is a new object

array([   1.,    4.,   16., -123.,   64.,  256.])

In [55]:
np.delete(f, 4) # f is not modified. This is a new object

array([ 1.,  4., 16., 64.])

In [56]:
m = np.random.poisson(2, 20)
print(m)
print(np.unique(m))
# Check out documentation for returning extra information such as number of occurrences of each value

[1 3 2 2 1 1 1 2 1 2 2 2 2 0 4 1 1 0 4 0]
[0 1 2 3 4]


### Exercise: reverse the following array by removing and inserting elements

In [57]:
reverse_me = np.arange(0, 100, 10)
reverse_me

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Moving elements around

In [58]:
print(g)

[0 1 2 3 4 5 6 7 8]


In [59]:
np.roll(g, 4)

array([5, 6, 7, 8, 0, 1, 2, 3, 4])

In [60]:
np.roll(g, -3)

array([3, 4, 5, 6, 7, 8, 0, 1, 2])

In [61]:
print(h)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
np.rot90(h)

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])

### Exercise: print all possible rolls of the following array

In [63]:
roll_me = np.arange(10)

# Indexing

Given an N-dimensional array, x, x[index] performs basic indexing, where index can be:

- integers
- slice objects
- numpy.newaxis objects (None)
- Ellipsis objects

Basic indexing will return a VIEW of the array (is a pointer that is pointing to the same memory where the original array is stored).

Advanced indexing is using a non-tuple object as index (such as boolean mask or integer indices of an array). Advanced indexing will always return a COPY of the original array.
Meaning that when you call a getattr of numpy class it will return a temporary copy (note that setattr is not returning anything)

Indexing with integers:

In [64]:
print(e)
for i in range(len(e)):
    print(e[i])

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
0.0
1.0
4.0
9.0
16.0
25.0
36.0
49.0
64.0
81.0


In [65]:
e_copy = np.copy(e)
print(e_copy)
print (e_copy[4])
e_copy[4] = 0
print(e_copy)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
16.0
[ 0.  1.  4.  9.  0. 25. 36. 49. 64. 81.]


Indexing with slices can be either using python slice object or a syntax  `:`. In the case of `:` it will take all the values in a given dimension

In [66]:
sl = slice(5, 0, -1) # start, end, step
print(e[sl])

[25. 16.  9.  4.  1.]


In [67]:
# Thes syntax ':' is identical to python slice object
print(e[5:0:-1])
print(e[:])

[25. 16.  9.  4.  1.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [68]:
e_copy = np.copy (e)
print(e_copy)
sl = slice(5, 0, -1) # start, end, step
print(e_copy[sl])
np.shares_memory(e_copy, e_copy[sl])
e_copy[sl][0] = 99
print(e_copy) #it changed!

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[25. 16.  9.  4.  1.]
[ 0.  1.  4.  9. 16. 99. 36. 49. 64. 81.]


`np.newaxis` (which is actually a descriptive name for `None`) increases the dimension of the array

In [69]:
print(e[:,np.newaxis])   # add axis after 
print(e[np.newaxis,...]) # add axis before

[[ 0.]
 [ 1.]
 [ 4.]
 [ 9.]
 [16.]
 [25.]
 [36.]
 [49.]
 [64.]
 [81.]]
[[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]]


Indexing with array will always return a copy

In [70]:
mask = [False, True, True, False, True, False, False, False, True, False]
mask = np.asarray(mask) # not really needed
print(e[mask])
e[mask][0] = 9999
print(e) #nothing changed!

[ 1.  4. 16. 64.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


### Multidimensional indexing 
Works similar as one dimensional indexing, you should provide indexing pattern per dimension (or use Ellipsis)

In [71]:
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [72]:
l[:, 2] # all rows, single column

array([0., 0., 1., 0.])

In [73]:
l[:, 0:2] # all rows, range of columns

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [74]:
l[:2, :] # range of rows, all columns

array([[1., 0., 0.],
       [0., 1., 0.]])

In [75]:
l[2:4, 0:2] # range of rows, range of columns

array([[0., 0.],
       [0., 0.]])

In [76]:
l[np.newaxis , 0]

array([[1., 0., 0.]])

## Broadcasting
It is a way how numpy treats arrays with different shapes during aritmethical operations. 
Two dimensionals are combatible if:
- they are equal
- one of them is scalar

The results will always have the shape of a larger array

In [77]:
a = np.arange(8)
b = np.arange(8)

In [78]:
#equal dimensions
ab = a*b
print(a.shape, b.shape, ab.shape)
#with a scalar
ascal = a*2
print(ascal.shape)

(8,) (8,) (8,)
(8,)


In [79]:
#works with N-D arrays as well
at = np.random.randint(0, 100, size=(2,3,4))
bt = np.random.randint(0, 100, size=(3,4))  # This is broadcasted to (1, 3, 4)
print(at.shape, bt.shape, (at*bt).shape)

(2, 3, 4) (3, 4) (2, 3, 4)


In [80]:
at = np.random.randint(0, 100, size=(2,1,4))# This is broadcasted to (2, 3, 4)
bt = np.random.randint(0, 100, size=(3,4))  # This is broadcasted to (1, 3, 4)
print(at)
print(bt)
print(at*bt)
print(at.shape, bt.shape, (at*bt).shape)

[[[78 52 49 57]]

 [[69 19 74 55]]]
[[46  3 70 23]
 [49 77 49 51]
 [56  0 27 37]]
[[[3588  156 3430 1311]
  [3822 4004 2401 2907]
  [4368    0 1323 2109]]

 [[3174   57 5180 1265]
  [3381 1463 3626 2805]
  [3864    0 1998 2035]]]
(2, 1, 4) (3, 4) (2, 3, 4)


### Exercise:
- can you multiply an array of shape (4, 2) with one of shape (4, 2, 1)?
- can you multiply an array of shape (4, 2) with one of shape (4, 1, 2)?
- can you multiply an array of shape (4, 2) with one of shape (1, 4, 2)?

# Binary operations

In [81]:
n = np.random.choice([True, False], size=10)
o = np.random.choice([True, False], size=10)
print(n)
print(o)

[ True False  True  True  True False  True False  True False]
[ True False False  True False  True  True False False  True]


In [82]:
n & o

array([ True, False, False,  True, False, False,  True, False, False,
       False])

In [83]:
n | o

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True])

In [84]:
n ^ o

array([False, False,  True, False,  True,  True, False, False,  True,
        True])

In [85]:
~ n

array([False,  True, False, False, False,  True, False,  True, False,
        True])

### Exercise: implement a 3-bit xor by combining two-bit operators
```
False False False = False
False False  True =  True
False  True False =  True
 True False False =  True
False  True  True = False
 True  True False = False
 True False  True = False
 True  True  True = False
```

# Applying functions over arrays

### Extending a scalar function to an array

Probably the easiest way to apply a apply functions that operate over arrays is using `np.vectorize`. `np.vectorize` is a decorator to apply to a function that operates over a scalar. The result is a function that can operate over an arbitrary array at C-like speed

In [86]:
def myfunc(a, b):
    if   (a * b) % 3 == 0: return a - b
    elif a % 2           : return b - a
    else                 : return a + b
    
myfunc_vectorized = np.vectorize(myfunc)
# same as
#
# @np.vectorize
# def ...

In [87]:
p = np.random.randint(0, 10, 9).reshape(3, 3)
print("h = \n", h)
print("p = \n", p)

h = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
p = 
 [[6 6 6]
 [8 0 2]
 [0 7 1]]


In [88]:
try:
    myfunc(h, p)
except ValueError as error:
    print("Error:", error)

Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [89]:
myfunc_vectorized(h, p)

array([[-6, -5, -4],
       [-5,  4, -3],
       [ 6,  0,  9]])

### Applying functions over axes

In [90]:
np.apply_along_axis(np.sum, 1, h)

array([ 3, 12, 21])

In [91]:
np.apply_along_axis(np.sqrt, 1, h)
# This function operates element by element, therefore it change the shape!

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [92]:
def complex_operation_over_array(a):
    b = a[0] + a[2] - a[1]**2
    c = b ** 4
    return c

np.apply_along_axis(complex_operation_over_array, 1, h)

array([      1,    4096, 1500625])

### Applying different operations to different parts of the array

In [93]:
even = h % 2 == 0
odd  = ~even
np.piecewise(h, [even, odd], [np.negative, np.square])

array([[ 0,  1, -2],
       [ 9, -4, 25],
       [-6, 49, -8]])

### Exercise: create an array with two columns (mean and std) of each row of the following array. Repeat for columns

In [94]:
means   = np.random.uniform(10, 1000, 10)
stat_me = np.random.uniform(means, means**0.5, (20, means.size))

# Sorting, searching and counting

In [95]:
q = np.asarray([1, 3, 65, 2, -1, 4, -5, -10])
print(q)

[  1   3  65   2  -1   4  -5 -10]


In [96]:
np.sort(q)

array([-10,  -5,  -1,   1,   2,   3,   4,  65])

In [97]:
np.argsort(q)

array([7, 6, 4, 0, 3, 1, 5, 2])

In [98]:
q[np.argsort(q)]

array([-10,  -5,  -1,   1,   2,   3,   4,  65])

In [99]:
r = np.copy(q)
r.sort() # sort in-place
r

array([-10,  -5,  -1,   1,   2,   3,   4,  65])

In [100]:
print(np.max(q), np.argmax(q))

65 2


In [101]:
print(np.min(q), np.argmin(q))

-10 7


In [102]:
np.where(q % 2 == 0, q**2, -q)

array([ -1,  -3, -65,   4,   1,  16,   5, 100])

In [103]:
print(h)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [104]:
np.argwhere(h % 2 == 0) # each entry is a set of indices that point to the element

array([[0, 0],
       [0, 2],
       [1, 1],
       [2, 0],
       [2, 2]])

In [105]:
print(mask)

[False  True  True False  True False False False  True False]


In [106]:
print(len(mask), np.count_nonzero(mask), np.count_nonzero(~mask))

10 4 6


In [107]:
to_search = [1, 2, 5, 6, 7, 10, 11, 14, 15, 66]
good_ones = [5, 10, 15]
np.in1d(to_search, good_ones)

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [108]:
np.isnan([1, 3, np.nan, 4])

array([False, False,  True, False])

### Find the indices of the nan value in the following array. Try to do it in two different ways

In [109]:
find_the_nan = np.random.uniform(0, 100, 100000)
true_index   = np.random.randint(0,      100000)
find_the_nan[true_index] = np.nan
true_index

9485

# Others

In [110]:
print(r, len(r))

[-10  -5  -1   1   2   3   4  65] 8


In [111]:
s = np.diff(r)
print(s, len(s))

[ 5  4  2  1  1  1 61] 7


In [112]:
np.clip(r, -2, 5)

array([-2, -2, -1,  1,  2,  3,  4,  5])

In [113]:
heights, bin_edges = np.histogram(r, 20, (-10, 20))

In [114]:
x_pos = np.asarray([1, 4,  4])
y_pos = np.asarray([5, 2, -1])
np.linalg.norm(x_pos - y_pos) # Euclidean distance

6.708203932499369

In [115]:
bins = [-10, 0, 10, 20]
np.digitize(r, bins) # ask which bin each value falls into 0 = underflow, len(bins) = overflow

array([1, 1, 1, 2, 2, 2, 2, 4])

In [116]:
np.floor(4.4), np.ceil(4.6)

(4.0, 5.0)

In [117]:
np.round(1.234)

1.0

In [118]:
np.round(1.23456789, decimals=6)

1.234568

# Random number generation

In [119]:
np.random

<module 'numpy.random' from '/home/gonzalo/sw/anaconda3/envs/IC-3.7-2018-11-14/lib/python3.7/site-packages/numpy/random/__init__.py'>

In [120]:
np.random.exponential(4) # sample from a exponential distribution with scale value 4

1.9362641152115523

In [121]:
np.random.normal(5, 1.1) # sample from a gaussian with mean 5 and sigma 1.1

3.9423931455462915

In [122]:
np.random.poisson(5.3) # sample from a poisson with mean 5.3

5

# For testing

There are some utilities in numpy to compare numbers: `np.isclose`, `np.allclose`.
The first is used to compare two numbers or two arrays element by element. The second one is equivalent to `all(np.isclose(a, b))`.

In [123]:
a = np.random.uniform(1, 2    , size=10)
b = np.random.normal (0, 1e-13, size=10)
print("Element by element", np.isclose (a, a + b))
print("All together      ", np.allclose(a, a + b))

Element by element [ True  True  True  True  True  True  True  True  True  True]
All together       True


The function is parametrizable with two tolerances: an absolute one and a relative one and it checks
$$|a - b| \leq a_{tol} + r_{tol} \cdot |b|$$
The values default to $a_{tol} = 10^{-8}$ and $r_{tol} = 10^{-5}$

In [124]:
print("Element by element", np.isclose (a, a + b, atol=0, rtol=1e-13))
print("All together      ", np.allclose(a, a + b, atol=0, rtol=1e-13))

Element by element [ True False False False  True  True  True  True  True  True]
All together       False


In [125]:
print("Element by element", np.isclose (a, a + b, atol=1e-13, rtol=0))
print("All together      ", np.allclose(a, a + b, atol=1e-13, rtol=0))

Element by element [False False False False  True  True  True  True False False]
All together       False
